name: Swift Build and Tests

on:
  push:
    branches:
      - master

jobs:
  job-nomipro:
    runs-on: macos-latest

    strategy:
        matrix:
          destination: ['platform=iOS Simulator,name=iPhone 11']

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Build and test
        run: |
          xcodebuild clean test -project nomipro.xcodeproj -scheme nomipro -destination "${destination}" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO
        env:
         destination: ${{ matrix.destination }}

      - name: Slack Notification
        uses: homoluctus/slatify@master
        if: failure()
        with:
          type: ${{ job.status }}
          job_name: "なんかエラー https://github.com/${{ github.repository }}/commit/${{ github.sha }}/checks"
          username: "GitHub Actions"
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
